language: objective-c
osx_image: xcode9.3beta
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- bundle install
- bundle exec pod repo update
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false